// No 'use client' directive: this is a plain module (not a component), same
// convention as lib/local-cache.ts / lib/usePullToRefresh.ts. It is only
// ever imported from 'use client' components, but importing it does not
// itself require the directive.

/**
 * Registers public/sw.js (generated by scripts/gen-sw.mjs). Gated on
 * production only — Turbopack's dev server rewrites chunk contents behind
 * stable URLs, so a cache-first worker active during `next dev` would mask
 * live edits behind stale cached responses (Pitfall 5).
 *
 * `onUpdateAvailable` fires once a NEW worker version reaches the
 * 'installed' state while an existing controller is already active — that
 * combination is precisely an update, not a first install (a first install
 * has no controller yet, since nothing has claimed this page).
 */
export function registerServiceWorker(onUpdateAvailable: () => void): void {
  if (process.env.NODE_ENV !== 'production') return
  if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) return

  navigator.serviceWorker.register('/sw.js').then((registration) => {
    registration.addEventListener('updatefound', () => {
      const installing = registration.installing
      if (!installing) return
      installing.addEventListener('statechange', () => {
        if (installing.state === 'installed' && navigator.serviceWorker.controller) {
          onUpdateAvailable()
        }
      })
    })
  }, () => {
    // Registration failure — no worker, no offline shell. Nothing else in
    // the app depends on this succeeding, so fail silently (matches
    // lib/local-cache.ts's established safe-fallback convention).
  })
}

/**
 * Explicitly triggers a background update check on the current registration
 * (D-09) — called on the same foreground-boundary events FreshnessWatcher
 * already listens to, not left to the browser's default per-navigation
 * check alone. Swallows rejections; a failed check just means "no update
 * detected this time," never a thrown error surfaced to the caller.
 */
export function checkForUpdate(): void {
  if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) return
  navigator.serviceWorker.getRegistration().then((registration) => {
    registration?.update().catch(() => {})
  }, () => {})
}

/**
 * Activates a waiting service worker (D-07's "tap to refresh"). Posts the
 * SKIP_WAITING message, then reloads from a one-shot 'controllerchange'
 * listener — NOT immediately after posting — because the previous worker
 * keeps serving the page until that event actually fires.
 */
export function activateWaitingWorker(): void {
  if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) return
  navigator.serviceWorker.addEventListener('controllerchange', () => window.location.reload(), { once: true })
  navigator.serviceWorker.getRegistration().then((registration) => {
    registration?.waiting?.postMessage({ type: 'SKIP_WAITING' })
  }, () => {})
}
